### ISSUE TITLE
Migrations error in bot-bot job

### ISSUE THREAD

**Issue by mfansler** [conda-forge/status#145]
Monitoring R 4.3 migration, I noticed we stopped getting PRs the last couple days, despite fixing up stuff I identified as blocking. Having a look at recent `bot-bot` jobs showed they run ~5 mins, as opposed to the typical ~1 hr runtimes from a few days back. The `run migrations` section of the `bot-bot` logs shows the following error:

```bash
Run export START_TIME=$(date +%s)
  export START_TIME=$(date +%s)
  export TIMEOUT=7200
  export CIRCLE_BUILD_URL="[https://github.com/regro/cf-scripts/actions/runs/${RUN_ID}](https://github.com/regro/cf-scripts/actions/runs/$%7BRUN_ID%7D)"
  export CIRCLE_BUILD_NUM="actually-actions-${RUN_ID}"
  
  pushd cf-graph
  
  conda-forge-tick auto-tick
  
  popd
  shell: /usr/bin/bash -l {0}
  env:
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/micromamba-bin/.condarc
    CI_SKIP: 
    USERNAME: regro-cf-autotick-bot
    PASSWORD: ***
    RUN_ID: 5354311023
    MEMORY_LIMIT_GB: 7
    CF_TICK_GRAPH_DATA_BACKENDS: mongodb:file
    MONGODB_CONNECTION_STRING: ***
~/work/cf-scripts/cf-scripts/cf-graph ~/work/cf-scripts/cf-scripts
limit read as 7.0 GB
Setting memory limit to 6.0 GB
collapsing closed PR json
processing bot-rerun labels
Traceback (most recent call last):
  File "/home/runner/micromamba/envs/cf-scripts/bin/conda-forge-tick", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/cli.py", line 77, in main
    func(args)
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1489, in main
    _update_graph_with_pr_info()
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1471, in _update_graph_with_pr_info
    _update_nodes_with_bot_rerun(gx)
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1341, in _update_nodes_with_bot_rerun
    with node["payload"] as payload, payload["pr_info"] as pri, payload[
  File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/lazy_json_backends.py", line 636, in __getitem__
    return self._data[item]
KeyError: 'pr_info'
~/work/cf-scripts/cf-scripts
```

**Comment by beckermr** [comment]
This should be fixed now. Let's monitor it for several hours and we can close this if things seem ok.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Yeah have seen some migrator PRs opened. So think things are getting better 🙂

**Comment by jakirkham** [comment]
On a different note, it seems the status page isn't reflecting this issue

**Comment by beckermr** [comment]
Looks like it's working.

**Comment by beckermr** [comment]
Let's open a separate issue for the status page.

**Comment by beckermr** [comment]
Fixed with a python upgrade.

**Comment by jakirkham** [comment]
FWIW here's a recent R 4.3 migrator PR ( https://github.com/conda-forge/r-tigris-feedstock/pull/12 )

**Comment by mfansler** [comment]
Thank you!
