### ISSUE TITLE
Package upload failed after feedstock new version merge

### ISSUE THREAD

**Issue by JohannesBuchner** [conda-forge/status#166]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have this feedstock https://github.com/conda-forge/ultranest-feedstock
which recently had a new version https://github.com/conda-forge/ultranest-feedstock/pull/57 
which passed all checks (see checks tab).

Then I merged the PR.

This triggered Azure to run, which failed. The uploads failed, with the following error:
```
2024-02-17T09:58:22.1083829Z + upload_package --validate --feedstock-name=ultranest-feedstock /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml
2024-02-17T09:58:23.7409297Z Found git SHA 9a7db1870633449f05e81c95f2de89a5f849005c for this build!
2024-02-17T09:58:23.7410504Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T09:58:23.8845487Z WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
2024-02-17T09:58:24.0831875Z Adding in variants from internal_defaults
2024-02-17T09:58:24.0833502Z Adding in variants from /home/conda/feedstock_root/.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml
2024-02-17T09:58:27.0528283Z 
2024-02-17T09:58:27.1554365Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T09:58:27.2637095Z  53%|█████▎    | 1.47M/2.77M [00:00<00:00, 15.0MB/s]
2024-02-17T09:58:27.2637907Z 2.77MB [00:00, 13.9MB/s]                            
2024-02-17T09:58:57.5565660Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T09:58:57.5566662Z copy results:
2024-02-17T09:58:57.5567024Z {}
2024-02-17T09:58:57.5582298Z Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
2024-02-17T09:59:07.5700311Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T09:59:07.5715792Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T09:59:08.6038269Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T09:59:24.1037522Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T09:59:54.4544940Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:00:39.8358994Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:01:40.2148313Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:01:40.2152133Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:01:45.9368767Z 
2024-02-17T10:01:46.1103667Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:01:46.1104348Z 2.77MB [00:00, 16.8MB/s]                   
2024-02-17T10:02:16.3926577Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:02:16.3928152Z copy results:
2024-02-17T10:02:16.3928630Z {}
2024-02-17T10:02:16.3935544Z Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
2024-02-17T10:02:26.4053040Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:02:26.4062664Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:02:27.3371979Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:02:42.6699346Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:03:13.0191925Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:03:58.4011780Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:04:59.6654439Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:04:59.6655613Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:05:02.2981979Z 
2024-02-17T10:05:02.4767908Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:05:02.4769379Z 2.77MB [00:00, 16.3MB/s]                   
2024-02-17T10:05:32.7558568Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:05:32.7560350Z copy results:
2024-02-17T10:05:32.7587212Z {}
2024-02-17T10:05:32.7588382Z Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
2024-02-17T10:05:42.7692068Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:05:42.7698804Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:05:43.7635418Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:05:59.0742376Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:06:29.4048104Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:07:14.7489384Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:08:15.1089134Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:08:15.1092268Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:08:18.7909283Z 
2024-02-17T10:08:19.0093720Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:08:19.0094854Z 2.77MB [00:00, 13.3MB/s]                   
2024-02-17T10:08:49.3668415Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:08:49.3671897Z copy results:
2024-02-17T10:08:49.3673354Z {}
2024-02-17T10:08:49.3673820Z Failed to upload due to copy from staging to production channel failed. Trying again in 10 seconds
2024-02-17T10:08:59.3792754Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:09:00.2490345Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:09:00.3612362Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:09:15.6621538Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:09:46.0225237Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:10:31.3647779Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:11:31.7119422Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:11:31.7120663Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:11:35.2785348Z 
2024-02-17T10:11:35.5136666Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:11:35.5138141Z 2.77MB [00:00, 12.4MB/s]                   
2024-02-17T10:12:05.7812431Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:12:05.7815113Z copy results:
2024-02-17T10:12:05.7815568Z {}
2024-02-17T10:12:05.7821010Z Failed to upload due to copy from staging to production channel failed. Trying again in 16.4130859375 seconds
2024-02-17T10:12:22.2056750Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:12:22.2071732Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:12:23.1666714Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:12:38.5120135Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:13:08.8074655Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:13:54.1182659Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:14:54.7389617Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:14:54.7391381Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:14:58.5314896Z 
2024-02-17T10:14:58.7374968Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:14:58.7376012Z 2.77MB [00:00, 14.2MB/s]                   
2024-02-17T10:15:29.1103803Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:15:29.1104834Z copy results:
2024-02-17T10:15:29.1105321Z {}
2024-02-17T10:15:29.1109179Z Failed to upload due to copy from staging to production channel failed. Trying again in 28.722900390625 seconds
2024-02-17T10:15:57.8669139Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:15:57.8713305Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:15:58.8858709Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:16:14.1752727Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:16:44.5074149Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:17:29.9218630Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:18:30.2092554Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:18:30.2181252Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:18:33.8824458Z 
2024-02-17T10:18:34.0216554Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:18:34.0217192Z 2.77MB [00:00, 20.9MB/s]                   
2024-02-17T10:19:04.2961203Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:19:04.2962189Z copy results:
2024-02-17T10:19:04.2962493Z {}
2024-02-17T10:19:04.2967675Z Failed to upload due to copy from staging to production channel failed. Trying again in 50.26507568359375 seconds
2024-02-17T10:19:54.5977673Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:19:54.5989134Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:19:55.5862532Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:20:10.8911628Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:20:41.1824860Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:21:26.4727357Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:22:26.7934742Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:22:26.7937914Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:22:30.4252118Z 
2024-02-17T10:22:30.5914061Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:22:30.5915691Z 2.77MB [00:00, 17.5MB/s]                   
2024-02-17T10:23:00.8755588Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:23:00.8756772Z copy results:
2024-02-17T10:23:00.8778124Z {}
2024-02-17T10:23:00.8779237Z Failed to upload due to copy from staging to production channel failed. Trying again in 87.96388244628906 seconds
2024-02-17T10:24:28.9194787Z Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
2024-02-17T10:24:28.9206792Z INFO:binstar:Using Anaconda API: https://api.anaconda.org
2024-02-17T10:24:29.9115510Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
2024-02-17T10:24:45.2408026Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
2024-02-17T10:25:15.5387966Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
2024-02-17T10:26:00.9010407Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 60 seconds to try uploading again.
2024-02-17T10:27:01.2065999Z Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already exists on cf-staging. Waiting another 75 seconds to try uploading again.
2024-02-17T10:27:01.2067425Z WARNING: Distribution /home/conda/feedstock_root/build_artifacts/linux-64/ultranest-4.1.4-py310h1f7b6fc_0.conda already existed in cf-staging for a while. Deleting and re-uploading.
2024-02-17T10:27:04.8493553Z 
2024-02-17T10:27:05.0135620Z   0%|          | 0.00/2.77M [00:00<?, ?B/s]
2024-02-17T10:27:05.0137047Z 2.77MB [00:00, 17.8MB/s]                   
2024-02-17T10:27:35.6338939Z ERROR getting output validation information from the webservice: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
2024-02-17T10:27:35.6340057Z copy results:
2024-02-17T10:27:35.6340339Z {}
2024-02-17T10:27:35.6340622Z Failed to upload due to copy from staging to production channel failed. Trying again in 153.93679428100586 seconds
2024-02-17T10:30:09.3135578Z Traceback (most recent call last):
2024-02-17T10:30:09.3136950Z   File "/opt/conda/bin/upload_package", line 11, in <module>
2024-02-17T10:30:09.3137588Z     sys.exit(upload_package())
2024-02-17T10:30:09.3138516Z   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-02-17T10:30:09.3152063Z     return self.main(*args, **kwargs)
2024-02-17T10:30:09.3158536Z   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-02-17T10:30:09.3160787Z     rv = self.invoke(ctx)
2024-02-17T10:30:09.3164878Z   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-02-17T10:30:09.3165576Z     return ctx.invoke(self.callback, **ctx.params)
2024-02-17T10:30:09.3166162Z   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-02-17T10:30:09.3166607Z     return __callback(*args, **kwargs)
2024-02-17T10:30:09.3167142Z   File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 248, in upload_package
2024-02-17T10:30:09.3167918Z     retry_upload_or_check(
2024-02-17T10:30:09.3173523Z   File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 317, in retry_upload_or_check
2024-02-17T10:30:09.3174299Z     raise TimeoutError("Did not manage to upload package.  Failing.")
2024-02-17T10:30:09.3174897Z TimeoutError: Did not manage to upload package.  Failing.
```

This looks kind of similar to https://github.com/conda-forge/status/issues/153 or https://github.com/conda-forge/admin-requests/pull/779

What should I do? Is there a way to retry?

### Installed packages

```shell
github
```

### Environment info

```shell
github
```

**Comment by jakirkham** [comment]
There was an issue earlier that was fixed recently: https://github.com/conda-forge/status/issues/165

Please start a new build on CI. Can login to CI with GitHub login

**Comment by JohannesBuchner** [comment]
Thank you. 

Logging in after authorizing GitHub did not work (it says I have accounts with Microsoft, but then when I pick one it says "We couldn't find an account with that username."). 

I'll create a new package version and see if that works. Thanks again, @jakirkham
