### ISSUE TITLE
All builds are failing with an ImportError

### ISSUE THREAD

**Issue by isuruf** [conda-forge/status#183]
Failing with
```
+ setup_conda_rc /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_64_r_base4.3.yaml
Traceback (most recent call last):
  File "/opt/conda/bin/setup_conda_rc", line 7, in <module>
    from conda_forge_ci_setup.build_utils import setup_conda_rc
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 15, in <module>
    from conda_forge_ci_setup.upload_or_check_non_existence import retry_upload_or_check
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 18, in <module>
    import rattler_build_conda_compat.render
  File "/opt/conda/lib/python3.10/site-packages/rattler_build_conda_compat/render.py", line 23, in <module>
    from rattler_build_conda_compat.loader import parse_recipe_config_file
  File "/opt/conda/lib/python3.10/site-packages/rattler_build_conda_compat/loader.py", line 4, in <module>
    from typing import TYPE_CHECKING, Any, Iterator, Self
ImportError: cannot import name 'Self' from 'typing' (/opt/conda/lib/python3.10/typing.py)
```

**Comment by bp-kelley** [comment]
Minutes apart!  Anyway, this was my solution in case it helps:

```
diff --git a/.scripts/run_osx_build.sh b/.scripts/run_osx_build.sh
index ba0c879..7e8e725 100755
--- a/.scripts/run_osx_build.sh
+++ b/.scripts/run_osx_build.sh
@@ -22,6 +22,8 @@ bash $MINIFORGE_FILE -b -p ${MINIFORGE_HOME}
 
 source ${MINIFORGE_HOME}/etc/profile.d/conda.sh
 conda activate base
+# upgrade to python 3.11
+conda install -y  python==3.11
 export CONDA_SOLVER="libmamba"
 export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1
```

**Comment by bp-kelley** [comment]
But there might be a better way

**Comment by baszalmstra** [comment]
We are releasing a new version of `rattler-conda-build-compat`. Should be fixed asap!

**Comment by isuruf** [comment]
Fixed now

**Comment by baszalmstra** [comment]
Thanks @isuruf and our apologies! We have added a number of tests to ensure this doesnt happen again!

**Comment by jdblischak** [comment]
For anyone that installed the problematic rattler-build-conda-compat locally, here is how I updated my conda env (Python 3.10) to be able to run `conda smithy rerender` again:

```sh
mamba install rattler-build-conda-compat!=0.1.2
## - rattler-build-conda-compat    0.1.2  pyhd8ed1ab_0  conda-forge     Cached
## + rattler-build-conda-compat    0.0.6  pyhd8ed1ab_0  conda-forge       20kB

# These didn't work
mamba update
mamba install rattler-build-conda-compat
```
