### ISSUE TITLE
staged-recipes blocked up

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/status#5]
There are a couple of recipes that are still stuck in staged-recipes. Restarting the [build]( https://travis-ci.org/conda-forge/staged-recipes/jobs/153672103#L391 ) failed. Snippet of the traceback shown below.

```
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmp5236hjzg__feedstocks/eventlet-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

It is possible this was in part a consequence of trying to handle recipes that were already converted. Alternatively this could be caused by some issues with AppVeyor's API.

**Comment by jakirkham** [comment]
A new [build]( https://travis-ci.org/conda-forge/staged-recipes/builds/153689664 ) was created with the merge of PR ( https://github.com/conda-forge/staged-recipes/pull/1312 ) that does not have any of the converted feedstocks in it to finish the conversion. Will wait and see how that build progresses.

**Comment by jakirkham** [comment]
This appears to have resolved this issue. staged-recipes is now clear.

**Comment by jakirkham** [comment]
Running into this issue again. So am reopening. See this [build]( https://travis-ci.org/conda-forge/staged-recipes/jobs/153845433 ). Traceback included below. Have tried restarting once, but it failed. Will try again.

```
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 164, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/home/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 114, in add_project_to_appveyor
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ci.appveyor.com/api/projects
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/tmp/tmpu35f06wx__feedstocks/argparse-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

cc @msarahan

**Comment by jakirkham** [comment]
Tried to add PR ( https://github.com/conda-forge/staged-recipes/pull/1317 ) to ensure we were using the latest set of recipes at staged-recipes. It seems Travis CI likes to checkout commits now and so can sometimes be out-of-date. Doesn't appear this made any difference. See this [build]( https://travis-ci.org/conda-forge/staged-recipes/jobs/153849261 ), which has the same failure.

**Comment by jakirkham** [comment]
Attempting to temporarily remove `argparse` as it is having trouble getting converted ATM. Will try to re-add afterwards. See PR ( https://github.com/conda-forge/staged-recipes/pull/1318 ) for this temporary removal.

**Comment by jakirkham** [comment]
Removing `argparse` made no difference as the next recipe in the list has the same [problem]( https://travis-ci.org/conda-forge/staged-recipes/jobs/153850184 ). Went ahead and re-added `argparse` with PR ( https://github.com/conda-forge/staged-recipes/pull/1319 ).

**Comment by jakirkham** [comment]
Weird. Apparently after re-adding `argparse` we were able to get everything working again. All of the recipes are now converted.

**Comment by jakirkham** [comment]
xref: https://github.com/appveyor/ci/issues/1045 ?
